# This file was generated by GoReleaser. DO NOT EDIT.
cask "noxdir-nightly" do
  desc "Nightly build of the terminal utility for visualizing file system usage."
  homepage "https://github.com/crumbyte/noxdir"
  version "0.6.0-nightly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noxdir"
  manpage "man/noxdir.1"
  bash_completion "completion/noxdir.bash"
  zsh_completion "completion/noxdir.zsh"
  fish_completion "completion/noxdir.fish"

  on_macos do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.6.0-nightly/noxdir-v0.6.0-nightly-Darwin_x86_64.tar.gz"
      sha256 "238f34657bdec7fa484a6e3bd76b2e15e2b596ee60245eb21bfdae8f4b74d2d3"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.6.0-nightly/noxdir-v0.6.0-nightly-Darwin_arm64.tar.gz"
      sha256 "478af1a8f732b57363f07459addb1cc407b6625b43c24ff6a1c652fdc5cea07e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.6.0-nightly/noxdir-v0.6.0-nightly-Linux_x86_64.tar.gz"
      sha256 "54485846e219ff6b8d6ae00c794219bdabca5b739c28d9130f91d81991e75eff"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.6.0-nightly/noxdir-v0.6.0-nightly-Linux_arm64.tar.gz"
      sha256 "b80e39bee8d4fb35d89443f2243ca793e82a15edc08600a2d9898cd3f055f6a6"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
    end
  end

  # No zap stanza required
end
