# This file was generated by GoReleaser. DO NOT EDIT.
cask "noxdir" do
  desc "Terminal utility for visualizing file system usage."
  homepage "https://github.com/crumbyte/noxdir"
  version "0.5.0-nightly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noxdir"
  manpage "man/noxdir.1"
  bash_completion "completion/noxdir.bash"
  zsh_completion "completion/noxdir.zsh"
  fish_completion "completion/noxdir.fish"

  on_macos do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.5.0-nightly/noxdir- v0.5.0-nightly-Darwin_x86_64.tar.gz"
      sha256 "2143115f32a7dad96d1dbbd30617af16e159c1cc71c885b7a44cc80bb12092ee"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.5.0-nightly/noxdir- v0.5.0-nightly-Darwin_arm64.tar.gz"
      sha256 "af063f50c15780f04115fc0c4c4096b4338aa8b7dfe391a3fec94a5b2f1536cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.5.0-nightly/noxdir- v0.5.0-nightly-Linux_x86_64.tar.gz"
      sha256 "08f785947a17e8e4704a11c84edd6410a7c2b2d7f0b74fa3b3b8db8ddeacc27a"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.5.0-nightly/noxdir- v0.5.0-nightly-Linux_arm64.tar.gz"
      sha256 "43494b6ea57c49b085c4ff84408cf21c75a9931c951dcbeda1fc5fbf44760744"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
    end
  end

  # No zap stanza required
end
