# This file was generated by GoReleaser. DO NOT EDIT.
cask "noxdir" do
  desc "Terminal utility for visualizing file system usage."
  homepage "https://github.com/crumbyte/noxdir"
  version "0.5.0-nightly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noxdir"
  manpage "man/noxdir.1"
  bash_completion "completion/noxdir.bash"
  zsh_completion "completion/noxdir.zsh"
  fish_completion "completion/noxdir.fish"

  on_macos do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.5.0-nightly/noxdir- v0.5.0-nightly-Darwin_x86_64.tar.gz"
      sha256 "c866c04f72e24f5a2847bf24be2d6495b447a5eaa9f8e10cffa768967f691a06"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.5.0-nightly/noxdir- v0.5.0-nightly-Darwin_arm64.tar.gz"
      sha256 "315d781bfc6355ce6c784f2c75056155c45bcb8450515b12262ad27878418e87"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.5.0-nightly/noxdir- v0.5.0-nightly-Linux_x86_64.tar.gz"
      sha256 "48363ad1b0a3ac06c5c8cc83c6506dbe54904e5d9546175d381c550b6f5f288e"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.5.0-nightly/noxdir- v0.5.0-nightly-Linux_arm64.tar.gz"
      sha256 "5c023d34e6625aeb22efad57b16bd529ba68e3061870a8ca67c5a6360faf9c66"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
    end
  end

  # No zap stanza required
end
