# This file was generated by GoReleaser. DO NOT EDIT.
cask "noxdir" do
  desc "Terminal utility for visualizing file system usage."
  homepage "https://github.com/crumbyte/noxdir"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noxdir"
  manpage "man/noxdir.1"
  bash_completion "completion/noxdir.bash"
  zsh_completion "completion/noxdir.zsh"
  fish_completion "completion/noxdir.fish"

  on_macos do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.2.0/noxdir_Darwin_x86_64.tar.gz"
      sha256 "5fb9d356cb0670b291ee26835382e015797437afab5ea8dc25f4cf7897131e92"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.2.0/noxdir_Darwin_arm64.tar.gz"
      sha256 "3242becbcda3044918e15003c7d7566dfd7fdf32ec42618d15f9ea5142ed9e09"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.2.0/noxdir_Linux_x86_64.tar.gz"
      sha256 "f3bf75346be729f202afc4825e9eea4a473ea89df03aa631ac061f9bc6dd3039"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.2.0/noxdir_Linux_arm64.tar.gz"
      sha256 "53b43c01d305cc60bae09c98444b93745832f6eab6d9f70f292aae6af3029633"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
    end
  end

  # No zap stanza required
end
