# This file was generated by GoReleaser. DO NOT EDIT.
cask "noxdir-nightly" do
  name "noxdir-nightly"
  desc "Nightly build of the terminal utility for visualizing file system usage."
  homepage "https://github.com/crumbyte/noxdir"
  version "0.12.0-nightly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noxdir"
  manpage "man/noxdir.1"
  bash_completion "completion/noxdir.bash"
  zsh_completion "completion/noxdir.zsh"
  fish_completion "completion/noxdir.fish"

  on_macos do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v#{version}/noxdir-v#{version}-Darwin_x86_64.tar.gz"
      sha256 "7df89a7a656bcf74c05a954e4c5a11453a2ebeb6ebe0980183e1f97e3146e098"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v#{version}/noxdir-v#{version}-Darwin_arm64.tar.gz"
      sha256 "c1b9df31ae711e1da1f5dd45f2f179f6e76603051cb13c99909b6ff9ad692d08"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v#{version}/noxdir-v#{version}-Linux_x86_64.tar.gz"
      sha256 "7d22c02a67b8e09f9f11442e631d083624506b4219c01cbd75e7b04db26979fb"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v#{version}/noxdir-v#{version}-Linux_arm64.tar.gz"
      sha256 "8115ba3873d5637b41db6fd2d36de23a6a6e0f6f1c5c86553e13ccea0e9f1865"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
    end
  end

  # No zap stanza required
end
