# This file was generated by GoReleaser. DO NOT EDIT.
cask "noxdir-nightly" do
  desc "Nightly build of the terminal utility for visualizing file system usage."
  homepage "https://github.com/crumbyte/noxdir"
  version "0.6.0-nightly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noxdir"
  manpage "man/noxdir.1"
  bash_completion "completion/noxdir.bash"
  zsh_completion "completion/noxdir.zsh"
  fish_completion "completion/noxdir.fish"

  on_macos do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.6.0-nightly/noxdir-v0.6.0-nightly-Darwin_x86_64.tar.gz"
      sha256 "ff5a4c44e4e3806d3b66dbcfcc324f8dc45a46746d3f680f8356fa4297ad0714"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.6.0-nightly/noxdir-v0.6.0-nightly-Darwin_arm64.tar.gz"
      sha256 "f566883685c17a6e2379ed7f20ee91c2907b16d8508fbd7a2d6b0234023af910"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.6.0-nightly/noxdir-v0.6.0-nightly-Linux_x86_64.tar.gz"
      sha256 "c6e86701038d45cc955ddcd1a21a42aa9868069551c75e485e7786c15231597e"
    end
    on_arm do
      url "https://github.com/crumbyte/noxdir/releases/download/v0.6.0-nightly/noxdir-v0.6.0-nightly-Linux_arm64.tar.gz"
      sha256 "022c668b440f1c994bd34b6979f2c210a39afb2f709f7398b730b3b2e2f3603c"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxdir"]
    end
  end

  # No zap stanza required
end
